require 'onthesnow/resort/info'
require 'onthesnow/resort/elevation'
require 'onthesnow/resort/lifts'
require 'onthesnow/resort/slopes'
require 'onthesnow/resort/snow'
require 'onthesnow/resort/weather'
require 'onthesnow/resort/resort'